### PR TITLE
Fix fan off appearance to match other tiles

### PR DESCRIPTION
**Pull request by doubleangels**
When using a fan entity in a tile, the disabled colors were set for the tile instead of the normal colors for an entity that is currently off.  This patch fixes this issue.

Current:
Screenshot 2024-03-04 180328

Fix:
Screenshot 2024-03-04 180442

### CODE REVIEW

**Comment by Nerwyn** [comment]
It's not broken, it's a compromise. The tile feature fan speed selector uses `--tile-color` for it's background color. This makes the fan speed selector tile feature look incorrect compared to all of the other native tile features. While this PR would make the tile match the other tile icons when off, it would make the tile feature not match.

As it is now:
image

With `--state-fan-off-color` removed (does the same thing as your PR)
image

If anything the Home Assistant devs need to fix the fan speed tile feature to not use the feature/tile color for it's background.

**Comment by Nerwyn** [comment]
A better compromise would be to set it to an intermediate color like `rgb(72, 74, 78)`

image

**Comment by Nerwyn** [comment]
@doubleangels I've released [1.5.3](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.5.3), which makes the tile off color consistent across all entities (like show above), except for that pesky fan speed selector background color.

**Comment by doubleangels** [comment]
Heck yeah, man! Thanks for that, I appreciate it.

**Pull request closed without merging**
